spring.application.name=racket-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/smashsense_racket_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
